name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  
dependencies:

  flutter:
    sdk: flutter

  fefufit_icons:
    path: ../

  flutter_svg: ^2.0.9
  url_launcher: ^6.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/