name: fefufit_icons
description: Fefufit icons pack.
version: 0.0.1

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  
  fonts:
    - family: FefuIcons
      fonts:
        - asset: assets/fonts/FefuIcons.ttf

  uses-material-design: true